#!/bin/bash

##############################################################################
# author: Stephan Engelmann alias Secuvim
# github: https://github.com/secuvim
#
# A custom terminal welcome prompt
#
# Gathering system information and displaying them whenever a terminal window
# is opened.
##############################################################################

colour="\e[01;34m"
host_name=$(hostname)
kernel=$(uname -r)
up_time=$(uptime -p | sed 's|up ||g' | awk -F ',' '{print $1 $2}')
num_packs=$(pacman -Qq | wc -l)
cpu_name=$(grep 'model name' /proc/cpuinfo | uniq | awk -F ':' '{print $2}' | awk -F 'CPU' '{print $1}' | sed 's|Intel(R) Core(TM) ||g')
ram_used=$(free -mt | grep Mem: | awk '{print $3}')
ram_total=$(free -mt | grep Mem: | awk '{print $2}')
root_space=$(df -h --output=fstype,size,used / | tail -n1 | awk '{ print $3" / "$2" ("$1")"}')

echo -e "${colour}       pro·gram·mer\e[00m"
echo -e "   ((            ____      ${colour}Hostname:\e[00m ${host_name}"
echo -e "  .-))-..       |#inc\     ${colour}Kernel:\e[00m   ${kernel}"
echo -e "  :----: ; ---> |class|    ${colour}Uptime:\e[00m   ${up_time}"
echo -e "  :    ;-       |  int|    ${colour}CPU:\e[00m     ${cpu_name}"
echo -e "   -..-         |_____|    ${colour}RAM:\e[00m      ${ram_used} / ${ram_total} MB"
echo -e "An organism that converts  ${colour}Shell:\e[00m    ${SHELL}"
echo -e "    caffeine into code     ${colour}Root:\e[00m     ${root_space}"
echo
