#!/bin/bash
sudo /opt/glassfish4/bin/asadmin start-database
echo
/opt/glassfish4/bin/asadmin start-domain --debug registry
echo
/opt/glassfish4/bin/asadmin start-domain --debug adapter
echo
/opt/glassfish4/bin/asadmin start-domain --debug store
echo
/opt/glassfish4/bin/asadmin start-domain --debug enterprise
echo
/opt/glassfish4/bin/asadmin start-domain --debug web
echo
/opt/glassfish4/bin/asadmin start-domain --debug cocome-pickup
