#!/bin/bash
sudo /opt/glassfish4/bin/asadmin start-database
echo
/opt/glassfish4/bin/asadmin start-domain registry
echo
/opt/glassfish4/bin/asadmin start-domain adapter
echo
/opt/glassfish4/bin/asadmin start-domain store
echo
/opt/glassfish4/bin/asadmin start-domain enterprise
echo
/opt/glassfish4/bin/asadmin start-domain web
echo
/opt/glassfish4/bin/asadmin start-domain cocome-pickup
