#!/bin/bash
echo cocome-pickup
/opt/glassfish4/bin/asadmin stop-domain cocome-pickup
echo
echo web
/opt/glassfish4/bin/asadmin stop-domain web
echo
echo enterprise
/opt/glassfish4/bin/asadmin stop-domain enterprise
echo
echo store
/opt/glassfish4/bin/asadmin stop-domain store
echo
echo adapter
/opt/glassfish4/bin/asadmin stop-domain adapter
echo
echo registry
/opt/glassfish4/bin/asadmin stop-domain registry
#echo
echo database
/opt/glassfish4/bin/asadmin stop-database
